name: Run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Tests a executer'
        required: false
        default: 'integration'
        type: choice
        options:
          - integration
          - all

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run all Cypress tests
        if: ${{ github.event.inputs.scope == 'all' }}
        run: npx cypress run

      - name: Run integration feature tests only
        if: ${{ github.event.inputs.scope == 'integration' }}
        run: npx cypress run --spec 'cypress/integration/features/**/*.feature'
